CC = gcc

BINARIES = echo_various_methods
SOURCES = echo_various_methods.c
OBJECTS = echo_various_methods.o

all: echo_various_methods

echo_various_methods: $(OBJECTS)

$(OBJECTS):$(SOURCES)

clean:
	rm $(BINARIES) $(OBJECTS)
