CC = gcc

all: simpleclient simpleIPv4Client

simpleLocalClient: simpleLocalClient.o
simpleIPv4Client: simpleIPv4Client.o

simpleLocalClient.o: simpleLocalClient.c
simpleIPv4Client.o: simpleIPv4Client.c

clean:
	rm *.o simpleclient simpleIPv4Client